// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pacientes.Persistence.Context;

namespace Pacientes.Persistence.Migrations
{
    [DbContext(typeof(PacientesContext))]
    [Migration("20220208120058_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Pacientes.Domain.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<int>("CEP")
                        .HasColumnType("int");

                    b.Property<string>("CNS")
                        .HasColumnType("longtext");

                    b.Property<string>("CPF")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeMae")
                        .HasColumnType("longtext");

                    b.Property<string>("RG")
                        .HasColumnType("longtext");

                    b.Property<string>("Sexo")
                        .HasColumnType("longtext");

                    b.Property<string>("UF")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bairro = "Maysa 1",
                            CEP = 75380000,
                            CNS = "123456",
                            CPF = "79341014069",
                            Cidade = "Trindade",
                            DataNascimento = new DateTime(1989, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Rua Aliança, QD XX LT XX",
                            Nome = "Paulo Vitor Nunes do Nascimento",
                            NomeMae = "Maria Nunes",
                            RG = "123456",
                            Sexo = "m",
                            UF = "GO"
                        },
                        new
                        {
                            Id = 2,
                            Bairro = "Maysa 1",
                            CEP = 75380000,
                            CNS = "987654",
                            CPF = "20202126099",
                            Cidade = "Trindade",
                            DataNascimento = new DateTime(1989, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Rua Aliança, QD XX LT XX",
                            Nome = "Ariane Tabata",
                            NomeMae = "Ana Rita",
                            RG = "987654",
                            Sexo = "f",
                            UF = "GO"
                        });
                });

            modelBuilder.Entity("Pacientes.Domain.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("DDD")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("PacienteId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Telefones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DDD = 62,
                            Numero = 992929292,
                            PacienteId = 1,
                            Tipo = "Celular"
                        },
                        new
                        {
                            Id = 2,
                            DDD = 62,
                            Numero = 991919191,
                            PacienteId = 2,
                            Tipo = "Celular"
                        });
                });

            modelBuilder.Entity("Pacientes.Domain.Telefone", b =>
                {
                    b.HasOne("Pacientes.Domain.Paciente", "Paciente")
                        .WithMany("Telefones")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Pacientes.Domain.Paciente", b =>
                {
                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
