// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pacientes.Persistence.Context;

namespace Pacientes.Persistence.Migrations
{
    [DbContext(typeof(PacientesContext))]
    partial class PacientesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Pacientes.Domain.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Bairro")
                        .HasColumnType("TEXT");

                    b.Property<int>("CEP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CNS")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endereco")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMae")
                        .HasColumnType("TEXT");

                    b.Property<string>("RG")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sexo")
                        .HasColumnType("TEXT");

                    b.Property<string>("UF")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bairro = "Maysa 1",
                            CEP = 75380000,
                            CNS = "123456",
                            CPF = "79341014069",
                            Cidade = "Trindade",
                            DataNascimento = new DateTime(1989, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Rua Aliança, QD XX LT XX",
                            Nome = "Paulo Vitor Nunes do Nascimento",
                            NomeMae = "Maria Nunes",
                            RG = "123456",
                            Sexo = "Masculino",
                            UF = "GO"
                        },
                        new
                        {
                            Id = 2,
                            Bairro = "Maysa 1",
                            CEP = 75380000,
                            CNS = "987654",
                            CPF = "20202126099",
                            Cidade = "Trindade",
                            DataNascimento = new DateTime(1989, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Endereco = "Rua Aliança, QD XX LT XX",
                            Nome = "Ariane Tabata",
                            NomeMae = "Ana Rita",
                            RG = "987654",
                            Sexo = "Feminino",
                            UF = "GO"
                        });
                });

            modelBuilder.Entity("Pacientes.Domain.Telefone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DDD")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Numero")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tipo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Telefones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DDD = 62,
                            Numero = 992929292,
                            PacienteId = 1,
                            Tipo = "Celular"
                        },
                        new
                        {
                            Id = 2,
                            DDD = 62,
                            Numero = 991919191,
                            PacienteId = 2,
                            Tipo = "Celular"
                        });
                });

            modelBuilder.Entity("Pacientes.Domain.Telefone", b =>
                {
                    b.HasOne("Pacientes.Domain.Paciente", "Paciente")
                        .WithMany("Telefones")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("Pacientes.Domain.Paciente", b =>
                {
                    b.Navigation("Telefones");
                });
#pragma warning restore 612, 618
        }
    }
}
